config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  root 'pages#home'
  
  resources :categories

  resources :posts do
    resources :comments

    member do
      post :hide
      post :publish
    end

    resources :verifications do
      collection do
        post :generate_new_otp
      end
    end
  end
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :send_token_for_verification, only: %i[generate_new_otp]

  def new
    # If user authy is enabled, it will send token for verifications
    if current_user.authy_enabled?
      current_user.send_token_for_verification
    else
      flash.now[:error] = t(:verification_is_required)
    end
  end

  def create
    # Verify if user is authorized
    request_authy_validation

    if @request.success?
      # Change post to published
      @post.publish
      flash.now[:success] = t(:post_published)
      redirect_to post_path(@post)
    else
      flash.now[:error] = @request.errors.first.pop
      render :new, params: { post_id: @post.id }
    end
  end

  def generate_new_otp
    # Generating new OTP and sending it to user
    flash[:success] = t(:otp_sent)
    render :new, params: { post_id: @post.id }
  end

  private

  def send_token_for_verification
    current_user.send_token_for_verification
  end

  def request_authy_validation
    @request = Authy::API.verify(id: current_user.authy_id, token: params[:token])
    @request
  end

  def find_post
    @post = Post.friendly.find(params[:post_id])
  end
end

app/views/verifications/new.html.haml
.col-sm-6.col-sm-offset-3.custom-background
  %h2= t(:verify_account)
  %p= t(:ability_to_post)
  %hr
  = simple_form_for(:request, url: post_verifications_path, html: { class: 'form-horizontal'} ) do |f|
    .form-group
      .col-sm-12
        = text_field_tag :token, params[:token], required: true, label: false, placeholder: t(:otp_required), class: 'form-control col-md-10'

    .form-input
      = f.button :submit, t(:submit), class: 'btn btn-danger'
      = link_to t(:generate_new_otp), generate_new_otp_post_verifications_path, method: :post, post_id: params[:post_id], class: 'btn btn-default'