config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  root 'pages#home'
  
  resources :categories

  resources :posts do
    resources :comments

    member do
      post :hide
      post :publish
    end

    resources :verifications do
      collection do
        post :generate_new_otp
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Postable
  include Statusable

  extend FriendlyId
  friendly_id :title, use: %i[slugged finders]

  # Counter cache to count and save views directly
  is_impressionable counter_cache: true, column_name: :views

  belongs_to :user
  belongs_to :category

  has_many :comments, dependent: :destroy

  validates :title, length: { minimum: 2 }
  validates :description, length: { maximum: 450 }
  validates :content, length: { in: 6..5000 }

  validates_presence_of :title, :description, :content
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show
  load_and_authorize_resource

  def index
    # if user is superadmin then @posts will get all posts by all users [controlled by ability]
    @posts = @posts.order(created_at: :desc)
  end

  def show
    # Get category related posts
    @related = Post.related_posts(@post.category_id).limit(15)

    # Add impression (one viewer) to post
    impressionist(@post)
  end

  def create
    if @post.save
      flash[:success] = t(:successfully_created)
      # Will redirect to OTP verification page
      redirect_to new_post_verification_path(@post)
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = t(:successfully_updated)
      redirect_to post_path(@post)
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t(:deleted_successfully)
    else
      flash.now[:error] = @post.errors.full_messages
    end
    redirect_to root_path
  end

  def hide
    # Will hide post if its published
    if @post.hide
      flash[:success] = t(:post_is_hidden_now)
    else
      flash.now[:error] = @post.errors.full_messages
    end
    redirect_back fallback_location: post_path(@post)
  end

  def publish
    # It will republish post if its hidden
    if @post.publish
      flash[:success] = t(:post_published)
    else
      flash.now[:error] = @post.errors.full_messages
    end
    redirect_back fallback_location: post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :content).merge(category_id: params[:post][:category_id], user: current_user)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
- content_for :javascript_includes do
  = javascript_include_tag 'posts'
#post-form
  .col-sm-6.col-sm-offset-3.custom-background
    %h2{ 'data-typer': 'hello' }= @post.persisted? ? t(:modify) + @post.title : t(:create_post)
    %hr
    = simple_form_for(@post, html: { class: 'form-horizontal'} ) do |f|
      - if @post.errors.present?
        %ul{:class => "alert alert-danger"}
          - @post.errors.messages.each do |key, value|
            %li{style: 'margin-left: 5px;'}= "#{key.to_s} #{value.join(',')}"

      .form-group
        .col-sm-12
          = f.select :category_id, options_for_select(active_categories, @post.category_id), { include_blank: t(:select_category) }, class: 'form-control', id: 'selected'

      .form-group#title
        .col-sm-12
          = f.text_field :title, required: true, label: false, placeholder: t(:title), class: 'form-control col-md-10'

      .form-group#description
        .col-sm-12
          = f.text_area :description, required: true, label: false, placeholder: t(:description), class: 'form-control', rows: 3

      .form-group#content
        .col-sm-12
          = f.text_area :content, required: true, label: false, placeholder: t(:content), class: 'form-control', rows: 8

      .form-group#submit
        .col-sm-12
          = f.button :submit, t(:submit), class: 'form-control btn btn-danger'

app/views/posts/_post.html.haml
.container-fluid
  .row
    %p
      .post-description= simple_format(post.description)
    %p
      .post-content= simple_format(post.content)
%hr
  %small.category-posts
    = icon('fas', 'user', ownername(post))
  %small.category-posts
    = icon('fas', 'clock', convert_date_format(post.created_at))
  %small.category-posts
    = icon('fas', 'eye', post.views)
  - if owner?(post) || can?(:manage, post)
    .pull-right
      = render partial: 'post_options', locals: { post: post }
%hr

app/views/posts/_post_options.html.haml
= link_to edit_post_path(post), class: 'btn btn-warning btn-xs custom-button' do
  = icon('far', 'edit', "data-toggle": 'tooltip', "data-placement": 'top', title: t(:edit))

= link_to post_path(post), method: :delete, class: 'btn btn-danger btn-xs custom-button' do
  = icon('far', 'trash-alt', "data-toggle": 'tooltip', "data-placement": 'top', title: t(:delete))

- if post.hidden?
  = link_to publish_post_path(post), method: :post, class: 'btn btn-success btn-xs custom-button' do
    = icon('far', 'share-square', t(:publish))

- if post.drafted?
  = link_to new_post_verification_path(post), class: 'btn btn-info btn-xs custom-button' do
    = icon('far', 'check-circle', t(:verify))

- if post.published?
  = link_to hide_post_path(post), method: :post, class: 'btn btn-primary btn-xs custom-button' do
    = icon('far', 'eye-slash', t(:hide))

app/views/posts/_posts_list.html.haml
%table.table.table-bordered.table-hover
  %thead
    %tr.custom-head
      %th= t(:title)
      %th.text-center= t(:category)
      %th.text-center= t(:status)
      %th.text-center= t(:creation_date)
      %th.text-center= t(:options)
  %tbody
  - @posts.each do |post|
    %tr
      %td
        = link_to post.title, post
      %td.text-center
        = post.category.name
      %td.text-center
        %span{class: "label label-#{status_label(POST_STATUS.key(post.status))}"}
          = POST_STATUS.key(post.status).capitalize
      %td
        .text-center
          = convert_date_format(post.created_at)
      %td
        = render partial: 'post_options', locals: { post: post }

app/views/posts/_related_posts.html.haml
- @related.each do |post|
  %h5
    = link_to post_path(post) do
      = post.title
      %small= post.description.truncate(50, omission: " ... #{t(:continue_reading)}")
  %hr

app/views/posts/edit.html.haml
= render partial: 'form'

app/views/posts/index.html.haml
.container-fluid
  .custom-background
    .row
      .pull-left
        %h2= t(:manage_posts)
        %p= "#{t(:shared)} #{@posts.count} #{t(:posts).downcase}"
      .pull-right
        %h2
        = link_to new_post_path, class: 'btn btn-info btn-sm custom-button' do
          = icon('far','plus-square', t(:add))
    %hr
    .row
      - if @posts.present?
        = render partial: 'posts_list'
      - else
        .text-center
          = t(:no_data)

app/views/posts/new.html.haml
= render partial: 'form'

app/views/posts/show.html.haml
.col-sm-8
  .custom-background
    %h3
      = @post.title
      .pull-right
        %small
          = link_to @post.category.name, category_path(@post.category), class: 'label label-info'
    %hr
    = render partial: 'post', locals: { post: @post }

  -# Comments Section
  - if @post.published?
    .custom-background{style: 'margin-top:10px'}
      %h3
        .comments-section-head= t(:comments)
      %hr
      = render partial: 'comments/comments'


.col-sm-4
  .custom-background
    %h3= t(:related_posts)
    %hr
    = render partial: 'related_posts'