config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  root 'pages#home'
  
  resources :categories

  resources :posts do
    resources :comments

    member do
      post :hide
      post :publish
    end

    resources :verifications do
      collection do
        post :generate_new_otp
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include Statusable

  extend FriendlyId
  friendly_id :name, use: %i[slugged finders]

  has_many :posts

  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }

  before_destroy :check_associations_with_posts

  scope :active,    (-> { where(status: CATEGORIES_STATUS[:active]) })
  scope :inactive,  (-> { where(status: CATEGORIES_STATUS[:inactive]) })

  private

  def check_associations_with_posts
    return unless posts.present?
    throw(:abort)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :show
  load_and_authorize_resource

  def show
    check_category_status
    # get published posts in specific category
    @category_posts = @category.posts.published
    # get most recent posts for the category
    @recent = @category.posts.recent.order('RANDOM()').limit(15)
  end

  def create
    if @category.save
      flash[:success] = t(:successfully_created)
      redirect_to categories_path
    else
      flash.now[:error] = @category.errors.full_messages
      render :new
    end
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = t(:successfully_updated)
      redirect_to categories_path
    else
      flash.now[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t(:deleted_successfully)
    else
      # Flash error when trying to destroy a category that have posts
      flash[:alert] = t(:cannot_remove_category_associated_with_posts)
    end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :status)
  end

  def check_category_status
    # return user to main page if category is archived or inactive
    return if @category.active?
    redirect_to root_path
  end
end

app/views/categories/_categories_list.html.haml
%table.table.table-bordered.table-hover
  %thead
    %tr.custom-head
      %th= t(:category_name)
      %th= t(:posts_shared)
      %th= t(:status)
      %th= t(:options)
  %tbody
  - @categories.each do |category|
    %tr
      %td= category.name
      %td
        = category.posts.count
        = t(:posts)
      %td
        = CATEGORIES_STATUS.key(category.status).capitalize
      %td
        = link_to edit_category_path(category), class: 'btn btn-warning btn-xs custom-button' do
          = icon('far', 'edit', "data-toggle": 'tooltip', "data-placement": 'top', title: t(:edit))
        = link_to category_path(category), method: :delete, class: 'btn btn-danger btn-xs custom-button' do
          = icon('far', 'trash-alt', "data-toggle": 'tooltip', "data-placement": 'top', title: t(:delete))

app/views/categories/_category_posts_list.html.haml
.container-fluid
  - @category_posts.each do |post|
    .row
      %h4
        = link_to post_path(post) do
          = icon('fas', 'newspaper', post.title)
      %span
        = post.description.truncate(350, omission: " ... #{t(:continue_reading)}")
    .row
      %small.category-posts
        = icon('fas', 'user', ownername(post))
      %small.category-posts
        = icon('fas', 'clock', convert_date_format(post.created_at))
    %hr

app/views/categories/_form.html.haml
- content_for :javascript_includes do
  = javascript_include_tag 'categories'

.col-sm-6.col-sm-offset-3.custom-background
  %h2{ 'data-typer': 'hello' }= @category.persisted? ? t(:modify) + @category.name : t(:create_category)
  %hr
  = simple_form_for(@category) do |f|
    = f.error_notification

    .form-inputs#category-name
      .col-sm-12
        = f.input :name, required: true, label: false, placeholder: t(:category_name), autofocus: true, class: 'form-control'

    .form-inputs#category-status
      .col-sm-12
        = f.select :status, options_for_select(statuses, (@category.status if @category.persisted?)), { include_blank: t(:please_select_status) }, class: 'form-control'

    .form-inputs#submit-category
      .col-sm-12
        %br
        = f.button :submit, t(:submit), class: 'form-control btn btn-danger'

app/views/categories/_recent_posts.html.haml
- @recent.each do |post|
  %h5
    = link_to '#' do
      = post.title
      %small= post.description.truncate(50, omission: " ... #{t(:continue_reading)}")
    %small
      ,
      = ownername(post)
      /
      = t(:shared_this)
      = time_ago_in_words(post.created_at)
  %hr

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
.container-fluid
  .custom-background
    .row
      .pull-left
        %h2= t(:categories)
        %p= t(:listing_all_categories)
      .pull-right
        %h2
        = link_to new_category_path, class: 'btn btn-info btn-sm custom-button' do
          = icon('far','plus-square', t(:add))
    %hr
    .row
      - if @categories.present?
        = render partial: 'categories_list'
      - else
        .text-center
          = t(:no_data)

app/views/categories/new.html.haml
= render 'form'

app/views/categories/show.html.haml
.col-sm-8
  .custom-background
    %h3
      = @category.name
      %small= t(:category)
    %hr
    = render partial: 'category_posts_list'

.col-sm-4
  .custom-background
    %h3= t(:most_recent)
    %hr
    = render partial: 'recent_posts'