config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  root 'pages#home'
  
  resources :categories

  resources :posts do
    resources :comments

    member do
      post :hide
      post :publish
    end

    resources :verifications do
      collection do
        post :generate_new_otp
      end
    end
  end
end

app/views/layouts/navbar/_categories.html.haml
- active_categories.each do |category_name, category_id|
  %li
    = link_to category_name, category_path(find_category(category_id))

app/views/layouts/navbar/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed.custom-navbar
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Blog'n Post", root_path, class: 'navbar-brand logo'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.dropdown
          = link_to '#', class: 'dropdown-toggle', "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"  do
            = icon('fas', 'briefcase', t(:categories))

          %ul.dropdown-menu
            = render partial: 'layouts/navbar/categories'
        - if user_signed_in?
          %li
            = link_to new_post_path do
              = icon('fas', 'plus', t(:create_post))
      %ul.nav.navbar-nav.navbar-right
        = render partial: 'layouts/navbar/user_menu'

app/views/layouts/navbar/_user_menu.html.haml
- if user_signed_in?
  %li
    = link_to edit_user_registration_path do
      = icon('fas', 'user', (current_user.try(:username) || current_user.email).capitalize)
  %li.dropdown
    = link_to '#', class: 'dropdown-toggle', "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"  do
      = icon('fas', 'bars', t(:menu))

    %ul.dropdown-menu
      %li
        = link_to edit_user_registration_path do
          = icon('fas', 'cogs', t(:settings))

      - if can?(:manage, Category)
        %li
          = link_to categories_path do
            = icon('fas', 'list-alt', t(:manage_categories))

      - if can?(:manage, Post, user_id: current_user.id)
        %li
          = link_to posts_path do
            = icon('fas', 'file-alt', t(:manage_posts))

      %li.divider{:role => "separator"}
      %li
        = link_to destroy_user_session_path, method: :delete do
          = icon('fas', 'sign-out-alt', t(:sign_out))
- else
  %li
    = link_to new_user_session_path do
      = icon('fas', 'sign-in-alt', t(:sign_in))
  %li
    = link_to new_user_registration_path do
      = icon('fas', 'user-plus', t(:sign_up))